# Meta Data for SEO

## Homepage
title = "Planter"
titleSeparator = "-"
titleAddition = "Documentation"
description = "Need help using Planter? You've come to the right place."
logo = "<svg width=\"113\" height=\"22\" viewBox=\"0 0 59.8 11.64\" xmlns=\"http://www.w3.org/2000/svg\"><g stroke-width=\".19\" aria-label=\"Planter\" fill=\"currentColor\"><path d=\"M29.04 12.97v6.106h-3.571V1.746h6.761q1.952 0 3.428.714 1.488.714 2.285 2.035.797 1.31.797 2.988 0 2.547-1.75 4.023-1.738 1.464-4.82 1.464zm0-2.892h3.19q1.416 0 2.154-.667.75-.666.75-1.904 0-1.274-.75-2.059-.75-.785-2.071-.809H29.04zM44.59 19.08h-3.452V.8h3.452zM54.89 19.08q-.238-.464-.345-1.155-1.25 1.393-3.25 1.393-1.892 0-3.141-1.095-1.238-1.095-1.238-2.761 0-2.047 1.512-3.142 1.524-1.095 4.392-1.107h1.583v-.738q0-.893-.464-1.428-.453-.536-1.44-.536-.87 0-1.37.417-.487.417-.487 1.143h-3.44q0-1.119.69-2.071.69-.952 1.952-1.488 1.262-.547 2.833-.547 2.381 0 3.773 1.202 1.405 1.19 1.405 3.357v5.582q.012 1.833.512 2.773v.202zm-2.845-2.392q.762 0 1.405-.333.643-.346.952-.917v-2.214h-1.286q-2.583 0-2.75 1.785l-.012.202q0 .643.453 1.06t1.238.416zM63.69 6.198l.107 1.488Q65.178 5.96 67.5 5.96q2.047 0 3.047 1.202t1.024 3.595v8.32h-3.44V10.84q0-1.095-.476-1.583-.476-.5-1.583-.5-1.452 0-2.178 1.238v9.082h-3.44V6.197zM78.31 3.031v3.166h2.202V8.72H78.31v6.428q0 .714.274 1.024.274.31 1.047.31.571 0 1.012-.084v2.607q-1.012.31-2.083.31-3.618 0-3.69-3.654V8.72h-1.881V6.2h1.88V3.033zM88.35 19.31q-2.833 0-4.618-1.738-1.774-1.738-1.774-4.63v-.333q0-1.94.75-3.464.75-1.535 2.119-2.357 1.38-.834 3.142-.834 2.642 0 4.154 1.667 1.524 1.665 1.524 4.724v1.405h-8.201q.166 1.262 1 2.023.845.762 2.13.762 1.989 0 3.108-1.44l1.69 1.893q-.774 1.095-2.095 1.714-1.321.607-2.928.607zm-.393-10.57q-1.024 0-1.666.69-.63.69-.81 1.976h4.786v-.273q-.024-1.143-.62-1.762-.594-.631-1.69-.631zM102.9 9.423q-.702-.095-1.238-.095-1.952 0-2.559 1.32v8.428h-3.44V6.196h3.249l.095 1.535q1.036-1.774 2.87-1.774.57 0 1.07.154z\" style=\"font-feature-settings:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-variant-numeric:normal\" transform=\"scale(.5789)\"/></g><g fill=\"currentColor\"><g fill-rule=\"evenodd\"><path d=\"M9.889 6.081s-3.779-.26-3.795 2.784c-.002.38.378.76.758.762 3.298.02 3.037-3.547 3.037-3.547zM.02 6.081s3.779-.26 3.795 2.784c.002.38-.378.76-.758.762C-.24 9.647.02 6.08.02 6.08zM4.961.006s-4.564 3.539-.513 6.96c.333.28.694.268 1.011 0 4.05-3.421-.497-6.96-.497-6.96z\"/></g><path d=\"M4.584 7.737h.76v3.924h-.76z\"/></g></svg>"
logoUrl = "https://planter.garden"
images = ["cover.png"]

# mainSections
mainSections = ["docs"]

[social]
#  twitter = "getdoks"

# Doks (@thulite/doks-core)
[doks]
  # Color mode
  colorMode = "auto" # auto (default), light or dark
  colorModeToggler = true # true (default) or false (this setting is only relevant when colorMode = auto)

  # Navbar
  navbarSticky = true # true (default) or false
  containerBreakpoint = "lg" # "", "sm", "md", "lg" (default), "xl", "xxl", or "fluid"

  ## Button
  navBarButton = false # false (default) or true
  navBarButtonUrl = "/docs/prologue/introduction/"
  navBarButtonText = "Get started"

  # FlexSearch
  flexSearch = true # true (default) or false
  searchExclKinds = [] # list of page kinds to exclude from search indexing (e.g. ["home", "taxonomy", "term"] )
  searchExclTypes = [] # list of content types to exclude from search indexing (e.g. ["blog", "docs", "legal", "contributors", "categories"])
  showSearch = [] # [] (all pages, default) or homepage (optionally) and list of sections (e.g. ["homepage", "blog", "guides"])
  indexSummary = false # true or false (default); whether to index only the `.Summary` instead of the full `.Content`; limits the respective JSON field size and thus increases loading time

  ## Search results
  showDate = false # false (default) or true
  showSummary = true # true (default) or false
  searchLimit = 99 # 0 (no limit, default) or natural number

  # Global alert
  alert = false # false (default) or true
  alertDismissable = true # true (default) or false

  # Bootstrap
  bootstrapJavascript = false # false (default) or true

  # Nav
  sectionNav = ["docs"] # ["docs"] (default) or list of sections (e.g. ["docs", "guides"])
  toTopButton = false # false (default) or true
  breadcrumbTrail = false # false (default) or true
  headlineHash = true # true (default) or false
  scrollSpy = true # true (default) or false

  # Multilingual
  multilingualMode = false # false (default) or true
  showMissingLanguages = true # whether or not to show untranslated languages in the language menu; true (default) or false

  # Versioning
  docsVersioning = false # false (default) or true
  docsVersion = "1.0"

  # UX
  headerBar = false # true (default) or false
  backgroundDots = true # true (default) or false

  # Homepage
  sectionFooter = false # false (default) or true

  # Blog
  relatedPosts = false # false (default) or true
  imageList = true # true (default) or false
  imageSingle = true # true (default) or false

  # Repository
  editPage = false # false (default) or true
  lastMod = false # false (default) or true
  repoHost = "GitHub" # GitHub (default), Gitea, GitLab, Bitbucket, or BitbucketServer
  docsRepo = "https://github.com/h-enk/doks"
  docsRepoBranch = "main" # main (default), master, or <branch name>
  docsRepoSubPath = "" # "" (none, default) or <sub path>

  # SCSS colors
  # backGround = "yellowgreen"
  ## Dark theme
  # textDark = "#dee2e6" # "#dee2e6" (default), "#dee2e6" (orignal), or custom color
  # accentDark = "#5d2f86" # "#5d2f86" (default), "#5d2f86" (original), or custom color
  ## Light theme
  # textLight = "#1d2d35" # "#1d2d35" (default), "#1d2d35" (orignal), or custom color
  # accentLight = "#8ed6fb" # "#8ed6fb" (default), "#8ed6fb" (orignal), or custom color

  # [doks.menu]
  #   [doks.menu.section]
  #     auto = true # true (default) or false
  #     collapsibleSidebar = true # true (default) or false

# Debug
[render_hooks.image]
  errorLevel = 'ignore' # ignore (default), warning, or error (fails the build)

[render_hooks.link]
  errorLevel = 'ignore' # ignore (default), warning, or error (fails the build)
  highlightBroken = false # true or false (default)

# Images (@thulite/images)
[thulite_images]
  [thulite_images.defaults]
    decoding = "async" # sync, async, or auto (default)
    fetchpriority = "auto" # high, low, or auto (default)
    loading = "lazy" # eager or lazy (default)
    widths = [480, 576, 768, 1025, 1200, 1440] # [640, 768, 1024, 1366, 1600, 1920] for example
    sizes = "auto" # 100vw (default), 75vw, or auto for example
    process = "" # "fill 1600x900" or "fill 2100x900" for example
    lqip = "16x webp q20" # "16x webp q20" or "21x webp q20" for example

# Inline SVG (@thulite/inline-svg)
[inline_svg]
  iconSetDir = "tabler-icons" # "tabler-icons" (default)

# SEO (@thulite/seo)
[seo]
  [seo.title]
    separator = " | "
    suffix = ""
  [seo.favicons]
    sizes = []
    icon = "favicon.png" # favicon.png (default)
    svgIcon = "favicon.svg" # favicon.svg (default)
    maskIcon = "mask-icon.svg" # mask-icon.svg (default)
    maskIconColor = "white" # white (default)
  [seo.schemas]
    type = "Organization" # Organization (default) or Person
    logo = "favicon-512x512.png" # Logo of Organization — favicon-512x512.png (default)
    name = "Planter" # Name of Organization or Person
    sameAs = [] # E.g. ["https://github.com/thuliteio/thulite", "https://fosstodon.org/@thulite"]
    images = ["cover.png"] # ["cover.png"] (default)
    article = [] # Article sections
    newsArticle = [] # NewsArticle sections
    blogPosting = ["blog"] # BlogPosting sections
    product = [] # Product sections
